/*
 * This file is generated by jOOQ.
 */
package com.tpodman172.tsk2.infra.schema.rds.tables;


import com.tpodman172.tsk2.infra.schema.rds.Indexes;
import com.tpodman172.tsk2.infra.schema.rds.Keys;
import com.tpodman172.tsk2.infra.schema.rds.Tsk2;
import com.tpodman172.tsk2.infra.schema.rds.tables.records.ChallengeHistoryRecord;

import java.sql.Date;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChallengeHistory extends TableImpl<ChallengeHistoryRecord> {

    private static final long serialVersionUID = 2075248845;

    /**
     * The reference instance of <code>tsk2.challenge_history</code>
     */
    public static final ChallengeHistory CHALLENGE_HISTORY = new ChallengeHistory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ChallengeHistoryRecord> getRecordType() {
        return ChallengeHistoryRecord.class;
    }

    /**
     * The column <code>tsk2.challenge_history.challenge_history_id</code>.
     */
    public final TableField<ChallengeHistoryRecord, Long> CHALLENGE_HISTORY_ID = createField(DSL.name("challenge_history_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>tsk2.challenge_history.task_id</code>.
     */
    public final TableField<ChallengeHistoryRecord, Long> TASK_ID = createField(DSL.name("task_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>tsk2.challenge_history.challenge_date</code>.
     */
    public final TableField<ChallengeHistoryRecord, Date> CHALLENGE_DATE = createField(DSL.name("challenge_date"), org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * The column <code>tsk2.challenge_history.created_at</code>.
     */
    public final TableField<ChallengeHistoryRecord, Timestamp> CREATED_AT = createField(DSL.name("created_at"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>tsk2.challenge_history.updated_at</code>.
     */
    public final TableField<ChallengeHistoryRecord, Timestamp> UPDATED_AT = createField(DSL.name("updated_at"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>tsk2.challenge_history</code> table reference
     */
    public ChallengeHistory() {
        this(DSL.name("challenge_history"), null);
    }

    /**
     * Create an aliased <code>tsk2.challenge_history</code> table reference
     */
    public ChallengeHistory(String alias) {
        this(DSL.name(alias), CHALLENGE_HISTORY);
    }

    /**
     * Create an aliased <code>tsk2.challenge_history</code> table reference
     */
    public ChallengeHistory(Name alias) {
        this(alias, CHALLENGE_HISTORY);
    }

    private ChallengeHistory(Name alias, Table<ChallengeHistoryRecord> aliased) {
        this(alias, aliased, null);
    }

    private ChallengeHistory(Name alias, Table<ChallengeHistoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> ChallengeHistory(Table<O> child, ForeignKey<O, ChallengeHistoryRecord> key) {
        super(child, key, CHALLENGE_HISTORY);
    }

    @Override
    public Schema getSchema() {
        return Tsk2.TSK2;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CHALLENGE_HISTORY_PRIMARY);
    }

    @Override
    public Identity<ChallengeHistoryRecord, Long> getIdentity() {
        return Keys.IDENTITY_CHALLENGE_HISTORY;
    }

    @Override
    public UniqueKey<ChallengeHistoryRecord> getPrimaryKey() {
        return Keys.KEY_CHALLENGE_HISTORY_PRIMARY;
    }

    @Override
    public List<UniqueKey<ChallengeHistoryRecord>> getKeys() {
        return Arrays.<UniqueKey<ChallengeHistoryRecord>>asList(Keys.KEY_CHALLENGE_HISTORY_PRIMARY);
    }

    @Override
    public ChallengeHistory as(String alias) {
        return new ChallengeHistory(DSL.name(alias), this);
    }

    @Override
    public ChallengeHistory as(Name alias) {
        return new ChallengeHistory(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ChallengeHistory rename(String name) {
        return new ChallengeHistory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ChallengeHistory rename(Name name) {
        return new ChallengeHistory(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Long, Date, Timestamp, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
