/*
 * This file is generated by jOOQ.
 */
package com.tpodman172.tsk2.infra.schema.rds.tables;


import com.tpodman172.tsk2.infra.schema.rds.Indexes;
import com.tpodman172.tsk2.infra.schema.rds.Keys;
import com.tpodman172.tsk2.infra.schema.rds.Tsk2;
import com.tpodman172.tsk2.infra.schema.rds.tables.records.CompletedDailyTaskRecord;

import java.sql.Date;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CompletedDailyTask extends TableImpl<CompletedDailyTaskRecord> {

    private static final long serialVersionUID = -1623541834;

    /**
     * The reference instance of <code>tsk2.completed_daily_task</code>
     */
    public static final CompletedDailyTask COMPLETED_DAILY_TASK = new CompletedDailyTask();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CompletedDailyTaskRecord> getRecordType() {
        return CompletedDailyTaskRecord.class;
    }

    /**
     * The column <code>tsk2.completed_daily_task.task_id</code>.
     */
    public final TableField<CompletedDailyTaskRecord, Long> TASK_ID = createField(DSL.name("task_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>tsk2.completed_daily_task.target_date</code>.
     */
    public final TableField<CompletedDailyTaskRecord, Date> TARGET_DATE = createField(DSL.name("target_date"), org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * The column <code>tsk2.completed_daily_task.created_at</code>.
     */
    public final TableField<CompletedDailyTaskRecord, Timestamp> CREATED_AT = createField(DSL.name("created_at"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>tsk2.completed_daily_task.updated_at</code>.
     */
    public final TableField<CompletedDailyTaskRecord, Timestamp> UPDATED_AT = createField(DSL.name("updated_at"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>tsk2.completed_daily_task</code> table reference
     */
    public CompletedDailyTask() {
        this(DSL.name("completed_daily_task"), null);
    }

    /**
     * Create an aliased <code>tsk2.completed_daily_task</code> table reference
     */
    public CompletedDailyTask(String alias) {
        this(DSL.name(alias), COMPLETED_DAILY_TASK);
    }

    /**
     * Create an aliased <code>tsk2.completed_daily_task</code> table reference
     */
    public CompletedDailyTask(Name alias) {
        this(alias, COMPLETED_DAILY_TASK);
    }

    private CompletedDailyTask(Name alias, Table<CompletedDailyTaskRecord> aliased) {
        this(alias, aliased, null);
    }

    private CompletedDailyTask(Name alias, Table<CompletedDailyTaskRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> CompletedDailyTask(Table<O> child, ForeignKey<O, CompletedDailyTaskRecord> key) {
        super(child, key, COMPLETED_DAILY_TASK);
    }

    @Override
    public Schema getSchema() {
        return Tsk2.TSK2;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.COMPLETED_DAILY_TASK_PRIMARY);
    }

    @Override
    public UniqueKey<CompletedDailyTaskRecord> getPrimaryKey() {
        return Keys.KEY_COMPLETED_DAILY_TASK_PRIMARY;
    }

    @Override
    public List<UniqueKey<CompletedDailyTaskRecord>> getKeys() {
        return Arrays.<UniqueKey<CompletedDailyTaskRecord>>asList(Keys.KEY_COMPLETED_DAILY_TASK_PRIMARY);
    }

    @Override
    public List<ForeignKey<CompletedDailyTaskRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CompletedDailyTaskRecord, ?>>asList(Keys.COMPLETED_DAILY_TASK_IBFK_1);
    }

    public Task task() {
        return new Task(this, Keys.COMPLETED_DAILY_TASK_IBFK_1);
    }

    @Override
    public CompletedDailyTask as(String alias) {
        return new CompletedDailyTask(DSL.name(alias), this);
    }

    @Override
    public CompletedDailyTask as(Name alias) {
        return new CompletedDailyTask(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CompletedDailyTask rename(String name) {
        return new CompletedDailyTask(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CompletedDailyTask rename(Name name) {
        return new CompletedDailyTask(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Date, Timestamp, Timestamp> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
