/*
 * This file is generated by jOOQ.
 */
package com.tpodman172.tsk2.infra.schema.rds.tables;


import com.tpodman172.tsk2.infra.schema.rds.Indexes;
import com.tpodman172.tsk2.infra.schema.rds.Keys;
import com.tpodman172.tsk2.infra.schema.rds.Tsk2;
import com.tpodman172.tsk2.infra.schema.rds.tables.records.TaskDailyProgressRecord;

import java.sql.Date;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TaskDailyProgress extends TableImpl<TaskDailyProgressRecord> {

    private static final long serialVersionUID = 1006754877;

    /**
     * The reference instance of <code>tsk2.task_daily_progress</code>
     */
    public static final TaskDailyProgress TASK_DAILY_PROGRESS = new TaskDailyProgress();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TaskDailyProgressRecord> getRecordType() {
        return TaskDailyProgressRecord.class;
    }

    /**
     * The column <code>tsk2.task_daily_progress.task_id</code>.
     */
    public final TableField<TaskDailyProgressRecord, Long> TASK_ID = createField(DSL.name("task_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>tsk2.task_daily_progress.completed</code>.
     */
    public final TableField<TaskDailyProgressRecord, Byte> COMPLETED = createField(DSL.name("completed"), org.jooq.impl.SQLDataType.TINYINT, this, "");

    /**
     * The column <code>tsk2.task_daily_progress.target_date</code>.
     */
    public final TableField<TaskDailyProgressRecord, Date> TARGET_DATE = createField(DSL.name("target_date"), org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * The column <code>tsk2.task_daily_progress.created_at</code>.
     */
    public final TableField<TaskDailyProgressRecord, Timestamp> CREATED_AT = createField(DSL.name("created_at"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>tsk2.task_daily_progress.updated_at</code>.
     */
    public final TableField<TaskDailyProgressRecord, Timestamp> UPDATED_AT = createField(DSL.name("updated_at"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>tsk2.task_daily_progress</code> table reference
     */
    public TaskDailyProgress() {
        this(DSL.name("task_daily_progress"), null);
    }

    /**
     * Create an aliased <code>tsk2.task_daily_progress</code> table reference
     */
    public TaskDailyProgress(String alias) {
        this(DSL.name(alias), TASK_DAILY_PROGRESS);
    }

    /**
     * Create an aliased <code>tsk2.task_daily_progress</code> table reference
     */
    public TaskDailyProgress(Name alias) {
        this(alias, TASK_DAILY_PROGRESS);
    }

    private TaskDailyProgress(Name alias, Table<TaskDailyProgressRecord> aliased) {
        this(alias, aliased, null);
    }

    private TaskDailyProgress(Name alias, Table<TaskDailyProgressRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TaskDailyProgress(Table<O> child, ForeignKey<O, TaskDailyProgressRecord> key) {
        super(child, key, TASK_DAILY_PROGRESS);
    }

    @Override
    public Schema getSchema() {
        return Tsk2.TSK2;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TASK_DAILY_PROGRESS_PRIMARY);
    }

    @Override
    public UniqueKey<TaskDailyProgressRecord> getPrimaryKey() {
        return Keys.KEY_TASK_DAILY_PROGRESS_PRIMARY;
    }

    @Override
    public List<UniqueKey<TaskDailyProgressRecord>> getKeys() {
        return Arrays.<UniqueKey<TaskDailyProgressRecord>>asList(Keys.KEY_TASK_DAILY_PROGRESS_PRIMARY);
    }

    @Override
    public List<ForeignKey<TaskDailyProgressRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TaskDailyProgressRecord, ?>>asList(Keys.TASK_DAILY_PROGRESS_IBFK_1);
    }

    public Task task() {
        return new Task(this, Keys.TASK_DAILY_PROGRESS_IBFK_1);
    }

    @Override
    public TaskDailyProgress as(String alias) {
        return new TaskDailyProgress(DSL.name(alias), this);
    }

    @Override
    public TaskDailyProgress as(Name alias) {
        return new TaskDailyProgress(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TaskDailyProgress rename(String name) {
        return new TaskDailyProgress(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TaskDailyProgress rename(Name name) {
        return new TaskDailyProgress(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Byte, Date, Timestamp, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
