/*
 * This file is generated by jOOQ.
 */
package com.tpodman172.tsk2.infra.schema.rds.tables;


import com.tpodman172.tsk2.infra.schema.rds.Indexes;
import com.tpodman172.tsk2.infra.schema.rds.Keys;
import com.tpodman172.tsk2.infra.schema.rds.Tsk2;
import com.tpodman172.tsk2.infra.schema.rds.tables.records.TaskProgressRecord;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TaskProgress extends TableImpl<TaskProgressRecord> {

    private static final long serialVersionUID = -1750689206;

    /**
     * The reference instance of <code>tsk2.task_progress</code>
     */
    public static final TaskProgress TASK_PROGRESS = new TaskProgress();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TaskProgressRecord> getRecordType() {
        return TaskProgressRecord.class;
    }

    /**
     * The column <code>tsk2.task_progress.task_id</code>.
     */
    public final TableField<TaskProgressRecord, Long> TASK_ID = createField(DSL.name("task_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>tsk2.task_progress.target_date</code>.
     */
    public final TableField<TaskProgressRecord, LocalDate> TARGET_DATE = createField(DSL.name("target_date"), org.jooq.impl.SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>tsk2.task_progress.completed</code>.
     */
    public final TableField<TaskProgressRecord, Boolean> COMPLETED = createField(DSL.name("completed"), org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>tsk2.task_progress.created_at</code>.
     */
    public final TableField<TaskProgressRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>tsk2.task_progress.updated_at</code>.
     */
    public final TableField<TaskProgressRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * Create a <code>tsk2.task_progress</code> table reference
     */
    public TaskProgress() {
        this(DSL.name("task_progress"), null);
    }

    /**
     * Create an aliased <code>tsk2.task_progress</code> table reference
     */
    public TaskProgress(String alias) {
        this(DSL.name(alias), TASK_PROGRESS);
    }

    /**
     * Create an aliased <code>tsk2.task_progress</code> table reference
     */
    public TaskProgress(Name alias) {
        this(alias, TASK_PROGRESS);
    }

    private TaskProgress(Name alias, Table<TaskProgressRecord> aliased) {
        this(alias, aliased, null);
    }

    private TaskProgress(Name alias, Table<TaskProgressRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TaskProgress(Table<O> child, ForeignKey<O, TaskProgressRecord> key) {
        super(child, key, TASK_PROGRESS);
    }

    @Override
    public Schema getSchema() {
        return Tsk2.TSK2;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TASK_PROGRESS_PRIMARY);
    }

    @Override
    public UniqueKey<TaskProgressRecord> getPrimaryKey() {
        return Keys.KEY_TASK_PROGRESS_PRIMARY;
    }

    @Override
    public List<UniqueKey<TaskProgressRecord>> getKeys() {
        return Arrays.<UniqueKey<TaskProgressRecord>>asList(Keys.KEY_TASK_PROGRESS_PRIMARY);
    }

    @Override
    public List<ForeignKey<TaskProgressRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TaskProgressRecord, ?>>asList(Keys.TASK_PROGRESS_IBFK_1);
    }

    public Task task() {
        return new Task(this, Keys.TASK_PROGRESS_IBFK_1);
    }

    @Override
    public TaskProgress as(String alias) {
        return new TaskProgress(DSL.name(alias), this);
    }

    @Override
    public TaskProgress as(Name alias) {
        return new TaskProgress(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TaskProgress rename(String name) {
        return new TaskProgress(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TaskProgress rename(Name name) {
        return new TaskProgress(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, LocalDate, Boolean, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
