/*
 * This file is generated by jOOQ.
 */
package com.tpodman172.tsk2.infra.schema.rds.tables.records;


import com.tpodman172.tsk2.infra.schema.rds.tables.TaskDailyProgress;

import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TaskDailyProgressRecord extends UpdatableRecordImpl<TaskDailyProgressRecord> implements Record5<Long, Byte, Date, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1617801442;

    /**
     * Setter for <code>tsk2.task_daily_progress.task_id</code>.
     */
    public void setTaskId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>tsk2.task_daily_progress.task_id</code>.
     */
    public Long getTaskId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>tsk2.task_daily_progress.completed</code>.
     */
    public void setCompleted(Byte value) {
        set(1, value);
    }

    /**
     * Getter for <code>tsk2.task_daily_progress.completed</code>.
     */
    public Byte getCompleted() {
        return (Byte) get(1);
    }

    /**
     * Setter for <code>tsk2.task_daily_progress.target_date</code>.
     */
    public void setTargetDate(Date value) {
        set(2, value);
    }

    /**
     * Getter for <code>tsk2.task_daily_progress.target_date</code>.
     */
    public Date getTargetDate() {
        return (Date) get(2);
    }

    /**
     * Setter for <code>tsk2.task_daily_progress.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>tsk2.task_daily_progress.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>tsk2.task_daily_progress.updated_at</code>.
     */
    public void setUpdatedAt(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>tsk2.task_daily_progress.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Date> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Byte, Date, Timestamp, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, Byte, Date, Timestamp, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TaskDailyProgress.TASK_DAILY_PROGRESS.TASK_ID;
    }

    @Override
    public Field<Byte> field2() {
        return TaskDailyProgress.TASK_DAILY_PROGRESS.COMPLETED;
    }

    @Override
    public Field<Date> field3() {
        return TaskDailyProgress.TASK_DAILY_PROGRESS.TARGET_DATE;
    }

    @Override
    public Field<Timestamp> field4() {
        return TaskDailyProgress.TASK_DAILY_PROGRESS.CREATED_AT;
    }

    @Override
    public Field<Timestamp> field5() {
        return TaskDailyProgress.TASK_DAILY_PROGRESS.UPDATED_AT;
    }

    @Override
    public Long component1() {
        return getTaskId();
    }

    @Override
    public Byte component2() {
        return getCompleted();
    }

    @Override
    public Date component3() {
        return getTargetDate();
    }

    @Override
    public Timestamp component4() {
        return getCreatedAt();
    }

    @Override
    public Timestamp component5() {
        return getUpdatedAt();
    }

    @Override
    public Long value1() {
        return getTaskId();
    }

    @Override
    public Byte value2() {
        return getCompleted();
    }

    @Override
    public Date value3() {
        return getTargetDate();
    }

    @Override
    public Timestamp value4() {
        return getCreatedAt();
    }

    @Override
    public Timestamp value5() {
        return getUpdatedAt();
    }

    @Override
    public TaskDailyProgressRecord value1(Long value) {
        setTaskId(value);
        return this;
    }

    @Override
    public TaskDailyProgressRecord value2(Byte value) {
        setCompleted(value);
        return this;
    }

    @Override
    public TaskDailyProgressRecord value3(Date value) {
        setTargetDate(value);
        return this;
    }

    @Override
    public TaskDailyProgressRecord value4(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public TaskDailyProgressRecord value5(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public TaskDailyProgressRecord values(Long value1, Byte value2, Date value3, Timestamp value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TaskDailyProgressRecord
     */
    public TaskDailyProgressRecord() {
        super(TaskDailyProgress.TASK_DAILY_PROGRESS);
    }

    /**
     * Create a detached, initialised TaskDailyProgressRecord
     */
    public TaskDailyProgressRecord(Long taskId, Byte completed, Date targetDate, Timestamp createdAt, Timestamp updatedAt) {
        super(TaskDailyProgress.TASK_DAILY_PROGRESS);

        set(0, taskId);
        set(1, completed);
        set(2, targetDate);
        set(3, createdAt);
        set(4, updatedAt);
    }
}
