/*
 * This file is generated by jOOQ.
 */
package com.tpodman172.tsk2.infra.schema.rds.tables.records;


import com.tpodman172.tsk2.infra.schema.rds.tables.Task;

import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TaskRecord extends UpdatableRecordImpl<TaskRecord> implements Record4<Long, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = -428025346;

    /**
     * Setter for <code>tsk2.task.task_id</code>.
     */
    public void setTaskId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>tsk2.task.task_id</code>.
     */
    public Long getTaskId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>tsk2.task.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tsk2.task.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tsk2.task.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>tsk2.task.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>tsk2.task.updated_at</code>.
     */
    public void setUpdatedAt(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>tsk2.task.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, Timestamp, Timestamp> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, String, Timestamp, Timestamp> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Task.TASK.TASK_ID;
    }

    @Override
    public Field<String> field2() {
        return Task.TASK.TITLE;
    }

    @Override
    public Field<Timestamp> field3() {
        return Task.TASK.CREATED_AT;
    }

    @Override
    public Field<Timestamp> field4() {
        return Task.TASK.UPDATED_AT;
    }

    @Override
    public Long component1() {
        return getTaskId();
    }

    @Override
    public String component2() {
        return getTitle();
    }

    @Override
    public Timestamp component3() {
        return getCreatedAt();
    }

    @Override
    public Timestamp component4() {
        return getUpdatedAt();
    }

    @Override
    public Long value1() {
        return getTaskId();
    }

    @Override
    public String value2() {
        return getTitle();
    }

    @Override
    public Timestamp value3() {
        return getCreatedAt();
    }

    @Override
    public Timestamp value4() {
        return getUpdatedAt();
    }

    @Override
    public TaskRecord value1(Long value) {
        setTaskId(value);
        return this;
    }

    @Override
    public TaskRecord value2(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public TaskRecord value3(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public TaskRecord value4(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public TaskRecord values(Long value1, String value2, Timestamp value3, Timestamp value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TaskRecord
     */
    public TaskRecord() {
        super(Task.TASK);
    }

    /**
     * Create a detached, initialised TaskRecord
     */
    public TaskRecord(Long taskId, String title, Timestamp createdAt, Timestamp updatedAt) {
        super(Task.TASK);

        set(0, taskId);
        set(1, title);
        set(2, createdAt);
        set(3, updatedAt);
    }
}
