/*
 * This file is generated by jOOQ.
 */
package com.tpodman172.tsk2.infra.schema.rds.tables.records;


import com.tpodman172.tsk2.infra.schema.rds.enums.TaskCycleType;
import com.tpodman172.tsk2.infra.schema.rds.tables.Task;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TaskRecord extends UpdatableRecordImpl<TaskRecord> implements Record5<Long, String, TaskCycleType, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1741114271;

    /**
     * Setter for <code>tsk2.task.task_id</code>.
     */
    public void setTaskId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>tsk2.task.task_id</code>.
     */
    public Long getTaskId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>tsk2.task.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tsk2.task.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tsk2.task.cycle_type</code>.
     */
    public void setCycleType(TaskCycleType value) {
        set(2, value);
    }

    /**
     * Getter for <code>tsk2.task.cycle_type</code>.
     */
    public TaskCycleType getCycleType() {
        return (TaskCycleType) get(2);
    }

    /**
     * Setter for <code>tsk2.task.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>tsk2.task.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>tsk2.task.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>tsk2.task.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, String, TaskCycleType, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, String, TaskCycleType, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Task.TASK.TASK_ID;
    }

    @Override
    public Field<String> field2() {
        return Task.TASK.TITLE;
    }

    @Override
    public Field<TaskCycleType> field3() {
        return Task.TASK.CYCLE_TYPE;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Task.TASK.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Task.TASK.UPDATED_AT;
    }

    @Override
    public Long component1() {
        return getTaskId();
    }

    @Override
    public String component2() {
        return getTitle();
    }

    @Override
    public TaskCycleType component3() {
        return getCycleType();
    }

    @Override
    public LocalDateTime component4() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component5() {
        return getUpdatedAt();
    }

    @Override
    public Long value1() {
        return getTaskId();
    }

    @Override
    public String value2() {
        return getTitle();
    }

    @Override
    public TaskCycleType value3() {
        return getCycleType();
    }

    @Override
    public LocalDateTime value4() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value5() {
        return getUpdatedAt();
    }

    @Override
    public TaskRecord value1(Long value) {
        setTaskId(value);
        return this;
    }

    @Override
    public TaskRecord value2(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public TaskRecord value3(TaskCycleType value) {
        setCycleType(value);
        return this;
    }

    @Override
    public TaskRecord value4(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public TaskRecord value5(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public TaskRecord values(Long value1, String value2, TaskCycleType value3, LocalDateTime value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TaskRecord
     */
    public TaskRecord() {
        super(Task.TASK);
    }

    /**
     * Create a detached, initialised TaskRecord
     */
    public TaskRecord(Long taskId, String title, TaskCycleType cycleType, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Task.TASK);

        set(0, taskId);
        set(1, title);
        set(2, cycleType);
        set(3, createdAt);
        set(4, updatedAt);
    }
}
