/*
 * This file is generated by jOOQ.
 */
package com.tpodman172.tsk2.infra.schema.rds;


import com.tpodman172.tsk2.infra.schema.rds.tables.Task;
import com.tpodman172.tsk2.infra.schema.rds.tables.TaskProgress;
import com.tpodman172.tsk2.infra.schema.rds.tables.records.TaskProgressRecord;
import com.tpodman172.tsk2.infra.schema.rds.tables.records.TaskRecord;

import javax.annotation.processing.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>tsk2</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<TaskRecord, Long> IDENTITY_TASK = Identities0.IDENTITY_TASK;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TaskRecord> KEY_TASK_PRIMARY = UniqueKeys0.KEY_TASK_PRIMARY;
    public static final UniqueKey<TaskProgressRecord> KEY_TASK_PROGRESS_PRIMARY = UniqueKeys0.KEY_TASK_PROGRESS_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<TaskProgressRecord, TaskRecord> TASK_PROGRESS_IBFK_1 = ForeignKeys0.TASK_PROGRESS_IBFK_1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<TaskRecord, Long> IDENTITY_TASK = Internal.createIdentity(Task.TASK, Task.TASK.TASK_ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<TaskRecord> KEY_TASK_PRIMARY = Internal.createUniqueKey(Task.TASK, "KEY_task_PRIMARY", Task.TASK.TASK_ID);
        public static final UniqueKey<TaskProgressRecord> KEY_TASK_PROGRESS_PRIMARY = Internal.createUniqueKey(TaskProgress.TASK_PROGRESS, "KEY_task_progress_PRIMARY", TaskProgress.TASK_PROGRESS.TASK_ID, TaskProgress.TASK_PROGRESS.TARGET_DATE);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<TaskProgressRecord, TaskRecord> TASK_PROGRESS_IBFK_1 = Internal.createForeignKey(com.tpodman172.tsk2.infra.schema.rds.Keys.KEY_TASK_PRIMARY, TaskProgress.TASK_PROGRESS, "task_progress_ibfk_1", TaskProgress.TASK_PROGRESS.TASK_ID);
    }
}
