/*
 * This file is generated by jOOQ.
 */
package com.tpodman172.tsk2.infra.schema.rds;


import com.tpodman172.tsk2.infra.schema.rds.tables.ChallengeHistory;
import com.tpodman172.tsk2.infra.schema.rds.tables.Task;
import com.tpodman172.tsk2.infra.schema.rds.tables.records.ChallengeHistoryRecord;
import com.tpodman172.tsk2.infra.schema.rds.tables.records.TaskRecord;

import javax.annotation.processing.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>tsk2</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<ChallengeHistoryRecord, Long> IDENTITY_CHALLENGE_HISTORY = Identities0.IDENTITY_CHALLENGE_HISTORY;
    public static final Identity<TaskRecord, Long> IDENTITY_TASK = Identities0.IDENTITY_TASK;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChallengeHistoryRecord> KEY_CHALLENGE_HISTORY_PRIMARY = UniqueKeys0.KEY_CHALLENGE_HISTORY_PRIMARY;
    public static final UniqueKey<TaskRecord> KEY_TASK_PRIMARY = UniqueKeys0.KEY_TASK_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<ChallengeHistoryRecord, Long> IDENTITY_CHALLENGE_HISTORY = Internal.createIdentity(ChallengeHistory.CHALLENGE_HISTORY, ChallengeHistory.CHALLENGE_HISTORY.CHALLENGE_HISTORY_ID);
        public static Identity<TaskRecord, Long> IDENTITY_TASK = Internal.createIdentity(Task.TASK, Task.TASK.TASK_ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<ChallengeHistoryRecord> KEY_CHALLENGE_HISTORY_PRIMARY = Internal.createUniqueKey(ChallengeHistory.CHALLENGE_HISTORY, "KEY_challenge_history_PRIMARY", ChallengeHistory.CHALLENGE_HISTORY.CHALLENGE_HISTORY_ID);
        public static final UniqueKey<TaskRecord> KEY_TASK_PRIMARY = Internal.createUniqueKey(Task.TASK, "KEY_task_PRIMARY", Task.TASK.TASK_ID);
    }
}
