/*
 * This file is generated by jOOQ.
 */
package com.tpodman172.tsk2.infra.schema.rds;


import com.tpodman172.tsk2.infra.schema.rds.tables.Task;
import com.tpodman172.tsk2.infra.schema.rds.tables.TaskProgress;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in tsk2
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>tsk2.task</code>.
     */
    public static final Task TASK = Task.TASK;

    /**
     * The table <code>tsk2.task_progress</code>.
     */
    public static final TaskProgress TASK_PROGRESS = TaskProgress.TASK_PROGRESS;
}
